### ISSUE TITLE
Did not work for me :(

### ISSUE THREAD

**Issue by kpeterpaul** [jj4giya/ity#1]
I tried to run the program but I keep getting an error, I followed all the instructions. Don't know what I'm doing wrong.

**Comment by jj4giya** [comment]
Can you send me the error.log file?
Along with what OS.
Might have to discord and screenshare. Add me up (waffle#6514)

**Comment by jj4giya** [comment]
hi, if you were on mac, try the new version with the updated steps

**Comment by kpeterpaul** [comment]
https://user-images.githubusercontent.com/120349536/207229015-47a7c394-8f0d-4ed7-9039-3072d71be786.mp4

I attached a video of what happens when I try to run it after following the instructions (using windows).

**Comment by jj4giya** [comment]
Is there somewhere I can contact you faster?
Can you try right click and running it as administrator? Or shifting the ITY folder to Downloads or Desktop and running it.

**Comment by jj4giya** [comment]
hi @kpeterpaul , can you download the new version and give it a try? let me know if the problem is solved now

**Comment by kpeterpaul** [comment]
It works now! Thank you so much for your help and for this great program!
