### ISSUE TITLE
Recommendation to update README with some info regarding data download

### ISSUE THREAD

**Issue by gasharova** [jj4giya/ity#2]
Apparently you can download your data from the app as well. There the dialogue looks a little different but its easier to access than web so I assume some users will do that instead.

Theres a picker there for the time period and it would be nice to add a clarification to pick "all time" because I selected initially "last 1 year" and when I ran your program there was some inconsistencies, because of how following/unfollowing can happen with large time differences. 

Not an issue but it would be a good improvement IMO.

**Comment by jj4giya** [comment]
Mind telling me where exactly is this picker?
Cannot seem to locate it. Wonder if it's got something to do with me being on Android?
