### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by jackiekill** [jj4giya/ity#3]
I get the program up and loaded with my files but when I click the ITY button the program just quits unexpectedly. I am on Mac and it didn't direct me to download Rosetta when I right click opened the program,  I have an Apple M2 Chip so I thought it would. That could be the issue but I cannot find Rosetta anywhere to download to even try it.

**Comment by jj4giya** [comment]
Sorry I don't have a Mac so can't help with debugging

I made the Mac version using a VM so it's hard to pinpoint the issue since
practically there isn't any on mine

What you can do is drop your followers and following.html file to me and
I'll do it for you instead
