### ISSUE TITLE
No longer works due to change in Instagram's exporting - now uses date range

### ISSUE THREAD

**Issue by TheoreticalThreat** [jj4giya/ity#4]
Instagram no longer allows exporting of a simple list of current Following/Followers. 

Instead, it exports data within a selected date range, showing all Following/Followers activity for that range.

![image](https://github.com/jj4giya/ity/assets/39841027/dae0fc6f-2a09-49c0-931d-6dd4d45f46c6)

**Comment by jj4giya** [comment]
The whole point of this program is to use Instagram to download your Followers and Following file, then use my program to sort out and generate a list of the people who don't follow you back.

I'll update the instructions to download your data since it doesn't seem very clear.

**Comment by TheoreticalThreat** [comment]
> The whole point of this program is to use Instagram to download your Followers and Following file, then use my program to sort out and generate a list of the people who don't follow you back.
> 
> 
> 
> I'll update the instructions to download your data since it doesn't seem very clear.

I understand how the software works, I've used it successfully before. The issue is Instagram has changed how they export data.

If you export "All time" data for following/followers, it'll give you following/follower history since the beginning/all time instead of a list of accounts you currently follow and your followers. Same with any window of time that's selected for export. This causes ITY to not work properly on Windows and completely crash on macOS.

-------------------------------

My alternative to ITY, that's unfortunately no longer working, was running a Python script that uses Instaloader to generate a list of those who do not follow back, but it requires logging in, which is currently failing.

**Comment by jj4giya** [comment]
I'm sorry, I don't really understand your question. How have they changed the data that's exported? Everything still works for me on Windows.

I've been exporting follower and following list for "All time" ever since I developed this software.
